spring:
  config:
    import: optional:file:.env[.properties]
  application:
    # "DB_name" 대신, 일반 문자열로 지정 (테스트 시 편함)
    name: tcar

  datasource:
    driver-class-name: ${DB_driver}
    url: ${DB_url}
    username: ${DB_username}
    password: ${DB_password}

  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  redis:
    host: 127.0.0.1
    port: 6379
    # password: my_redis_password  # (비밀번호가 있다면)
  mail:
    host: smtp.gmail.com
    port: 587
    username: juryeong1@gmail.com
    password: eenkyzowstwkcuzg  # 오타 수정됨
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 이메일 인증 코드 만료시간 (30분)

coolsms:
  api:
    key: ${coolsms_key}
    secret: ${coolsms_secret_key}
    fromnum: ${fromnum}

jwt:
  secret:
    key: ${JWT_secret_key}

external:
  container:
    ip: ${container_ip}

pre-signed:
  url: ${pre_signed_url}

