spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: tcar

  datasource:
    driver-class-name: ${DB_driver}
    url: ${DB_url}
    username: ${DB_username}
    password: ${DB_password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    # password: ${REDIS_PASSWORD}  # 사용 시 활성화

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000 # 30분

coolsms:
  api:
    key: ${coolsms_key}
    secret: ${coolsms_secret_key}
    fromnum: ${fromnum}

jwt:
  secret:
    key: ${JWT_secret_key}

external:
  container:
    ip: ${container_ip}

pre-signed:
  url: ${pre_signed_url}
  protocol: ${PRE_SIGNED_PROTOCOL}
  host: ${PRE_SIGNED_HOST}
  port: ${PRE_SIGNED_PORT}
  context-path: ${PRE_SIGNED_CONTEXT_PATH}

logging:
  level:
    root: INFO
    com.hanbat.tcar: DEBUG
