spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ${DB_name}
  datasource:
    driver-class-name: ${DB_driver}
    url: ${DB_url}
    username: ${DB_username}
    password: ${DB_password}
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
